apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-git-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: git-content
          mountPath: /usr/share/nginx/html # Nginx sert les fichiers clonés

      - name: git-sync
        image: "registry.k8s.io/git-sync/git-sync:v4.2.3"
        args:
        - --repo=https://github.com/laurentpoirierfr/k8s-demystified
        - --root=/git/repo
        - --period=60s
        - --link=docs
        - --max-failures=1000000000
        - -v=2
        volumeMounts:
        - name: git-content
          mountPath: /git/repo # Le sidecar synchronise dans ce répertoire partagé

      volumes:
      - name: git-content
        emptyDir: {}

